### ISSUE TITLE
Package not found with composer require

### ISSUE THREAD

**Issue by DnD-Mimosa** [Vendic/magento2-checkout-only#1]
Hi,

First of all, thank you for this extension.

### Description

I tried to install your extension like it is recommended in your README with the following command :
`composer require vendic/magento2-checkoutonly`

### Expected result

Have your module installed in my vendors :D

### Actual result

Could not find a matching version of package vendic/magento2-checkoutonly. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

### Solution

Could you please add your module to packagist which will allow us to install it with composer require command. (https://packagist.org/search/?q=vendic%2Fmagento2-checkoutonly)

Thank you very much again !

BR.

**Comment by Tjitse-E** [comment]
Hi @DnD-Mimosa . I've added the package to packagist (https://packagist.org/packages/vendic/magento2-checkoutonly). Could you try again?

**Comment by DnD-Mimosa** [comment]
Hi @Tjitse-E ,

It works now 👍 

Thank you very much !
